easy_admin:
    design:
        brand_color: '#1e88e5'
        logo: 'favicon.ico'
    entities:
        App\Entity\User:
            label: 'Utilisateur'
            form:
                fields:
                    - {property: 'username'}
                    - {property: 'email'}
                    - {property: 'password'}
            list:
                fields:
                    - {property: 'username'}
                    - {property: 'email'}
            edit:
                fields:
                    - {property: 'username'}
                    - {property: 'email'}
                    - {property: 'password'}
            new:
                fields:
                    - {property: 'username'}
                    - {property: 'email'}
                    - {property: 'password'}
